const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
function receiptHtml(receipt, width, fontUrl, reprint = false) {
  if (receipt.status !== 'PAID' || !Array.isArray(receipt.items) || !receipt.items.length || !Number.isFinite(receipt.amount) || receipt.amount <= 0) throw new Error('Invalid paid receipt');
  for (const item of receipt.items) if (typeof item.name !== 'string' || !Number.isInteger(item.count) || item.count <= 0 || !Number.isFinite(item.subtotal) || item.subtotal < 0) throw new Error('Invalid receipt item');
  if (receipt.items.reduce((sum, i) => sum + i.subtotal, 0) !== receipt.amount) throw new Error('Receipt total mismatch');
  const paidDate = receipt.paidAt ? new Intl.DateTimeFormat('lo-LA', { dateStyle: 'short', timeStyle: 'short', timeZone: 'Asia/Vientiane' }).format(new Date(receipt.paidAt)) : '';
  const money = n => new Intl.NumberFormat('lo-LA').format(n) + ' ກີບ';
  const itemRows = receipt.items.map(item => `<tr class="item"><td class="name">${escape(item.name)}</td><td class="qty">${item.count}</td><td class="price">${money(item.subtotal / item.count)}</td><td class="amount">${money(item.subtotal)}</td></tr>`).join('');
  return `<!doctype html><html lang="lo"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:"><style>
  @font-face{font-family:Lao;src:url('${fontUrl}')} @page{margin:0} *{box-sizing:border-box} body{margin:0 auto;padding:4mm 3mm 6mm;width:${width}mm;font:11px Lao,sans-serif;color:#000;line-height:1.35} .center{text-align:center} .shop{margin:0;font-size:22px;font-weight:900;letter-spacing:.2px} .title{margin:1px 0 4px;font-size:14px;font-weight:800} .copy{font-size:10px} .meta{margin:3px 0;font-size:10px;line-height:1.5;overflow-wrap:anywhere} .rule{border:0;border-top:1px dashed #000;margin:7px 0} table{width:100%;border-collapse:collapse;table-layout:fixed} th{padding:2px 0 4px;font-size:10px;font-weight:800;border-bottom:1px solid #000} td{padding:4px 0;vertical-align:top;overflow-wrap:anywhere} .name{width:39%;text-align:left;padding-right:2px}.qty{width:10%;text-align:center}.price{width:24%;text-align:right;padding-right:2px}.amount{width:27%;text-align:right;white-space:nowrap}.item td{border-bottom:1px dotted #999}.total td{padding-top:7px;font-weight:900;font-size:14px;border-top:1px solid #000}.total .amount{font-size:15px}.payment{display:flex;justify-content:space-between;gap:8px;margin:7px 0 2px;font-weight:800}.payment span:last-child{text-align:right;overflow-wrap:anywhere} .thanks{margin:12px 0 0;font-size:12px;font-weight:800}.small{font-size:9px;margin-top:4px;overflow-wrap:anywhere}
  </style></head><body><header class="center"><h1 class="shop">4B POS</h1><div class="title">ໃບຮັບເງິນ</div>${reprint ? '<div class="copy">(ສຳເນົາ)</div>' : ''}</header><div class="meta"><div>ເລກບິນ: ${escape(receipt.orderNo)}</div><div>ວັນທີ: ${escape(paidDate)}</div></div><hr class="rule"><table><thead><tr><th class="name">ລາຍການ</th><th class="qty">ຈຳນວນ</th><th class="price">ລາຄາ</th><th class="amount">ລວມ</th></tr></thead><tbody>${itemRows}<tr class="total"><td colspan="3">ລວມທັງໝົດ</td><td class="amount">${money(receipt.amount)}</td></tr></tbody></table><div class="payment"><span>ວິທີຊຳລະ</span><span>${escape(receipt.paymentMethod || 'PhaJay')}</span></div><hr class="rule"><div class="center thanks">ຂອບໃຈທີ່ອຸດໜູນ</div><div class="center small">4B POS · ໃບບິນສຳເລັດແລ້ວ</div></body></html>`;
}
module.exports = { receiptHtml };
